// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE183508ConsoleEFApp.Models;

public partial class SiOrder
{
    public int OrderId { get; set; }

    public int? CustomerId { get; set; }

    public int? PromotionId { get; set; }

    public DateOnly? OrderDate { get; set; }

    public int? TotalAmount { get; set; }

    public int? Discount { get; set; }

    public string PaymentMethod { get; set; }

    public string PaymentStatus { get; set; }

    public string ShipmentStatus { get; set; }

    public virtual SiCustomer Customer { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public virtual Promotion Promotion { get; set; }
   
}