// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SE183508ConsoleEFApp.Models;

public delegate void MyDelegate(string msg);
public  class SiProduct
{   
    public static void Print(string msg) => Console.WriteLine(msg.ToUpper());
    public static void Show(string msg) => Console.WriteLine(msg.ToLower());
    public static void Display(string msg) => Console.WriteLine(msg);

    MyDelegate printValue = delegate (string val)
    {
        Console.WriteLine(val);
    };
    
    public int ProductId { get; set; }

    public string Name { get; set; }

    public int? CategoryId { get; set; }

    public string Description { get; set; }

    public string Barcode { get; set; }

    public double? Weight { get; set; }

    public int? CostPrice { get; set; }

    public int? GoldPrice { get; set; }

    public int? LaborCost { get; set; }

    public int? StoneCost { get; set; }

    public double? SellPriceRatio { get; set; }

    public virtual Category Category { get; set; }

    public virtual ICollection<OrderItem> OrderItems { get; set; } = new List<OrderItem>();

    public override string ToString()
    {
        return $"Name: {Name} Category: {Category} Description:" +
            $" {Description} Barcode: {Barcode} Weight: {Weight} CostPrice: {CostPrice}" +
            $" GoldPrice: {GoldPrice} LaborCost: {LaborCost} StoneCost: {StoneCost}";
    }
}